### ISSUE TITLE
Maybe issue 

### ISSUE THREAD

**Issue by omarbatao** [nutellinoit/sidecar-backup-volumes#1]
Hi @nutellinoit,

I'm trying to backup multiple folders, but on my s3 instance i've got only one backup pushed...

![schermata 2018-05-21 alle 14 43 14](https://user-images.githubusercontent.com/13422180/40308192-a3e472ae-5d05-11e8-968b-ac7adebd113a.png)
![schermata 2018-05-21 alle 14 42 53](https://user-images.githubusercontent.com/13422180/40308193-a3ffe174-5d05-11e8-946b-cfe29596c105.png)
![schermata 2018-05-21 alle 14 42 45](https://user-images.githubusercontent.com/13422180/40308194-a417fee4-5d05-11e8-85e7-7cb763efe3ad.png)
<img width="929" alt="schermata 2018-05-21 alle 14 44 51" src="https://user-images.githubusercontent.com/13422180/40308195-a430ca1e-5d05-11e8-8d30-980a0637a686.png">

**Comment by nutellinoit** [comment]
Can you try version 1.2 instead?

**Comment by omarbatao** [comment]
It's working 👍 Thanks!
